//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetE4
{
    using System;
    using System.Collections.Generic;
    
    public partial class livre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public livre()
        {
            this.reserver = new HashSet<reserver>();
        }
    
        public int idLivre { get; set; }
        public string titre { get; set; }
        public string auteur { get; set; }
        public int genre { get; set; }
        public int theme { get; set; }
        public string image { get; set; }
        public int quantite { get; set; }
    
        public virtual genrelivre genrelivre { get; set; }
        public virtual themelivre themelivre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserver> reserver { get; set; }
    }
}
